package io.github.patrikalm.model;

public class Person {


    private String firstName;   //has null or empty check
    private String lastName;    //has null or empty check
    private int id;             //has not a null or empty check. ID generated by database



    //constructor

    public Person(String firstName, String lastName) {

        setFirstName(firstName);
        setLastName(lastName);
    }
    // Used for verifying
    public Person() {

    }

    public Person(int id, String firstName, String lastName) {
        this(firstName, lastName);
        this.id = id;

    }

    //methods

       public String getFirstName() {

        return firstName;
    }

    public void setFirstName(String firstName) {

        if (firstName == null || firstName.trim().isEmpty())
            throw new IllegalArgumentException("Firstname can not be null or empty.");

        this.firstName = firstName;
    }

    public String getLastName() {

        return lastName;
    }

    public void setLastName(String lastName) {

        if (lastName == null || lastName.trim().isEmpty())
            throw new IllegalArgumentException("Lastname can not be null or empty.");

        this.lastName = lastName;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();

        sb.append(System.lineSeparator());
        sb.append("Name: ");
        sb.append(firstName);
        sb.append(" ");
        sb.append(lastName);
        sb.append(System.lineSeparator());
        sb.append(" with id: ");
        sb.append(getId());

        return sb.toString();
    }

    @Override
    public boolean equals(Object obj) {

        Person localPerson = (Person) obj;

        if (localPerson.id == 0 || localPerson.firstName.isEmpty()) {
            return false;
        }
        return this.firstName.equals(localPerson.firstName)
                && this.lastName.equals(localPerson.lastName)
                && this.id == localPerson.id;
    }


    @Override
    public int hashCode() {
        return firstName.hashCode() + lastName.hashCode() + id;
    }
}
